server:
  port: 8005                  # 指定该Eureka-Client的端口,8005

spring:
  application:
    name: cloud-register-user-metadata

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: 我是cloud-register-user-metadata #自定义的元数据，key/value都可以随便写。



