server:
  port:   8002                  # 指定该Eureka-Client的端口,8002

spring:
  application:
    name: cloud-register-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true


