server:
  port:   8010                # 指定该Eureka-Client的端口

spring:
  application:
    name: cloud-register-consumer-ribbon-without-eureka

cloud-register-user:
  ribbon:
    listOfServers: localhost:8002,localhost:8003

ribbon:
  eureka:
    enabled: false #不适用服务发现

eureka:
  client:
    registerWithEureka: false  #不注册
    fetchRegistry: false     #不获取注册信息
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true
