server:
  port: 8009                  # 指定该Eureka-Client的端口

spring:
  application:
    name: cloud-register-consumer-ribbon-configcustom

#cloud-register-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true


